<a href="https://colab.research.google.com/github/bbiblin/sic_ai_2025_sept/blob/main/BelenDiazClase_4_Actividad_SLIDES_76_106.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Clase 4 - Operaciones de matriz con Numpy

Hasta ahora, sabemos que NumPy es una biblioteca para Python, implementada en C la cual nos permite realizar operaciones ndarray de matrices multidimensionales rápidas y efectivas en la memoria. También nos permite usar funciones computacionales como álgebral lineal, generación de números random, etc.

### Operador +

En listas tradicionales: el operador '+' funciona de manera que concatena los elementos dados.

***Ejemplo en código***

In [ ]:
lista1 = [1, 2, 3]
lista2 = [4, 5, 6]
print("Lista + Lista:", lista1 + lista2) # esto imprimirá [1, 2, 3, 4, 5, 6]

Lista + Lista: [1, 2, 3, 4, 5, 6]


Mientras que en NumPy, el operador '+' suma los elementos.

In [ ]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print("Array + Array:", arr1 + arr2) # esto imprimirá [5, 7, 9]

Array + Array: [5 7 9]


Mientras las matrices tengan la misma forma, se pueden realizar operaciones aritméticas de suma, resta, multiplicación y división

In [ ]:

print("-----Array 1-----")
print(arr1.ndim) # esto muestra el número de dimensiones o ejes de la matriz, en este caso, 1
print(arr1.size) # esto imprime el tamaño de la matriz, en este caso, 3
print(arr1.shape) # imprime una tupla con la forma del array, en este caso, 3
print("-----Array 2-----")
print(arr2.ndim) # esto muestra el número de dimensiones o ejes de la matriz, en este caso, 1
print(arr2.size) # esto imprime el tamaño de la matriz, en este caso, 3
print(arr2.shape) # imprime una tupla con la forma del array, en este caso, 3

-----Array 1-----
1
3
(3,)
-----Array 2-----
1
3
(3,)


Procedemos a aplicar operaciones aritméticas

In [ ]:
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


#### Operador *

En listas tradicionales, el operador * significa "repetición"

In [ ]:
print("Lista * 3:", lista1 * 3) #esto imprime la lista repetida 3 veces

Lista * 3: [1, 2, 3, 1, 2, 3, 1, 2, 3]


Mientras que en NumPy, como vimos anteriormente, funciona para realizar operaciones matemáticas, en este caso, devuelve el resultado de la multiplicación de cada elemento.

In [ ]:
print("Array * 3:", arr1 * 3) # esto imprimirá [3, 6, 9]


Array * 3: [3 6 9]


### Repetir y mosaico

Numpy tiene su propio método para repetir elementos, con la función np.repeat(). Esta función, repite cada elemento, no el array como tal.

In [ ]:
# Creamos un array y lo almacenamos en la variable 'b'
b = np.array([1,2,3])
# np.repeat(array, cantidadRepeticiones) -> argumentos que recibe la función
np.repeat(b,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

 Le decimos que el array al que queremos aplicarle repeat es el array b (creado anteriormente), y queremos que cada elemento se repita 3 veces

Si lo que se desea es repetir la matriz o array como tal, para eso existe el método np.tile()

In [ ]:
# Le aplicaremos np.tile() al array creado anteriormente
# np.tile(array, cantidadRepeticiones) -> argumentos que recibe la función
np.tile(b,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

  Con np.tile(), la matriz también puede repetirse de forma bidimensional.

In [ ]:
C = np.arange(9) # esta línea crea un array con 9 elementos partiendo desde el 0 [0, 1, 2, 3, 4, 5, 6, 7, 8]
C = C.reshape(3,3) # esta función transforma las dimensiones del array, en este caso, lo convertimos en una matriz de 3x3
C.shape # esto imprime la forma del array
print(C) # imprime el contenido del array
print("----------------------")

print("Matriz Repetida")
c_repeat = np.tile(C, 3) # en este caso, np.tile repite la matriz 3 veces a lo largo del eje horizontal
#esto da como resultado de 3x9, donde cada fila se repite 3 veces.
print(c_repeat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
----------------------
Matriz Repetida
[[0 1 2 0 1 2 0 1 2]
 [3 4 5 3 4 5 3 4 5]
 [6 7 8 6 7 8 6 7 8]]


### Operador exponencial (**)

También, podemos realizar operaciones exponenciales con matrices.

In [ ]:
print(arr2)
print(arr1) # usaremos estos arrays definidos anteriormente para el ejemplo
print("---------------------------------------")
print("Array 2 elevando cada elemento al cuadrado")
arr2_elevado = arr2**2
print(arr2_elevado)
print("Divide cada elemento de arr1 entre el cuadrado del elemento correspondiente en arr2")
arr1_division = arr1/(arr2**2)
print(arr1_division)


[4 5 6]
[1 2 3]
---------------------------------------
Array 2 elevando cada elemento al cuadrado
[16 25 36]
Divide cada elemento de arr1 entre el cuadrado del elemento correspondiente en arr2
[0.0625     0.08       0.08333333]


### Operadores de comparación

También se pueden realizar operaciones de comparación con las matrices. Se comprueba si cada elemento del array cumple las condiciones, se devuelve True o False según corresponde.

In [ ]:
# Para el ejemplo de esta sección, crearemos un nuevo array
arr3= np.array([10,20,30,40])
arr3 # imprimimos el contenido del array
# aplicamos nuestra comparación

arr3_comparacion = arr3 > 10 #esta instrucción devolverá True o False, dependiendo del elemento y de si este es mayor a 10.
print(arr3)
print(arr3_comparacion)

[10 20 30 40]
[False  True  True  True]


####Notas

* NumPy realiza las operaciones matemáticas en cada elemento individualmente  
* Ambas arrays deben tener la misma forma para estas operaciones  
* Las operaciones con división convierten automáticamente a tipo float  

### Funciones Universales

Para esta sección, mostraremos la ufunc np.fix().
La función np.fix trunca la parte decimal de cada elemento, devolviendo la parte entera hacia cero.

In [ ]:
# Crear un array con números decimales
arr = np.array([3.14, 2.71, 5.99, -2.5, -1.8, 0.5])
print("Array original:", arr)

# Aplicar np.fix
resultado = np.fix(arr)
print("Después de np.fix:", resultado)

Array original: [ 3.14  2.71  5.99 -2.5  -1.8   0.5 ]
Después de np.fix: [ 3.  2.  5. -2. -1.  0.]


In [ ]:
# Array 2D con valores positivos y negativos
matriz = np.array([[1.7, -2.3, 4.9],
                   [-5.1, 6.8, -7.2],
                   [3.4, -0.5, 8.6]])

print("Matriz original:")
print(matriz)

print("\nMatriz después de np.fix:")
print(np.fix(matriz))

Matriz original:
[[ 1.7 -2.3  4.9]
 [-5.1  6.8 -7.2]
 [ 3.4 -0.5  8.6]]

Matriz después de np.fix:
[[ 1. -2.  4.]
 [-5.  6. -7.]
 [ 3. -0.  8.]]


### Métodos estadísticos

In [ ]:
x = np.arange(1,11) # esta línea crea un array de 11 elementos, partiendo desde el número 1
print(x)
suma_elementos = x.sum() # imprime el resultado de sumar todos los elementos del array
print("Elementos sumados")
print(suma_elementos)
promedio_elementos = x.mean() # imprime el promedio de todos los elementos del array
print("Promedio de los elementos")
print(promedio_elementos)

[ 1  2  3  4  5  6  7  8  9 10]
Elementos sumados
55
Promedio de los elementos
5.5


Podemos calcular las desviaciones de cada elemento, respecto a la media (5,5), así como también, sus desviaciones al cuadrado

In [ ]:
print("Desviaciones de cada elemento")
desviaciones_elemento = x - promedio_elementos
print(desviaciones_elemento)
print("Desviaciones de cada elemento al cuadrado")
desviaciones_cuadrado = (x - promedio_elementos) **2
print(desviaciones_cuadrado)
print("Suma de la desviación al cuadrado")
suma_desviaciones_cuadrado = desviaciones_cuadrado.sum()
print(suma_desviaciones_cuadrado)


Desviaciones de cada elemento
[-4.5 -3.5 -2.5 -1.5 -0.5  0.5  1.5  2.5  3.5  4.5]
Desviaciones de cada elemento al cuadrado
[20.25 12.25  6.25  2.25  0.25  0.25  2.25  6.25 12.25 20.25]
Suma de la desviación al cuadrado
82.5


Hay dos maneras de calcular la varianza con NumPy

In [ ]:
# 1era forma
varianza1 = desviaciones_cuadrado.sum() / x.size #la suma de las desviaciones al cuadrado divida por el número de matrices se denomina varianza
print(varianza1)

# 2da forma
varianza2 = x.var()
print(varianza2)

#Para encontrar la desviación estandar
desviacion_estandar1 = np.sqrt(x.var()) # esto calcula la raíz cuadrada de la varianza, la cual corresponde a la desviación estandar.
print(desviacion_estandar1)

# forma con método de NumPy
desviacion_estandar2 = x.std()
print(desviacion_estandar2)


8.25
8.25
2.8722813232690143
2.8722813232690143


Podemos calcular la suma acumulativa de todos los elementos de un array usando el método cumsum().  
Devuelve un nuevo array donde cada elemento en la posición i es la suma de todos los elementos desde el inicio del array hasta la posición i.

In [ ]:
suma_acumulada = x.cumsum()
print(suma_acumulada)

[ 1  3  6 10 15 21 28 36 45 55]


A continuación, veremos el uso de el método reshape(), el cual sirve para cambiar las dimensiones de un array

In [ ]:
# Creamos un array que va desde el 1 al 6
y = np.arange(1,7)
print(y)
# procedemos a convertir el array a uno bidimensional de 2x3
array_bidimensional = y.reshape(2,3)
print(array_bidimensional)

array_modificado = y.reshape(2, -1)
# Con esto, estamos especificando que queremos dos filas y dejamos que NumPy calcule automáticamente las columnas necesarias.
# Al haber 6 elementos y 2 filas, Numpy calcula: 6/2 = 3 columnas. Al imprimir esto, imprimirá lo mismo que el anterior array.
print(array_modificado)

array_modificado2 = y.reshape(3, -1)
# Aquí tenemos otro ejemplo; queremos 3 filas y dejamos que Numpy calcule automáticamente las columnas necesarias.
# Numpy calcula: 6/3 = 2 columnas.
print(array_modificado2)


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


Las funciones estadísticas de NumPy se pueden aplicar por fila y columna siempre y cuando le entreges como argumento el axis que deseas (0 = eje vertical, osea, columnas, y 1 = eje horizontal, osea, filas)

In [ ]:
y = y.reshape(2,3)
print(y)
# Calculamos el promedio de cada columna
prom_col = y.mean(axis=0)
print(prom_col)
# Y ahora calculamos el promedio de  cada fila
prom_fila = y.mean(axis=1)
print(prom_fila)

[[1 2 3]
 [4 5 6]]
[2.5 3.5 4.5]
[2. 5.]


### Números random en NumPy

np.random.seed() es un método de NumPy que inicializa el generador de números pseudoaleatorios. Establece un punto de partida fijo para la secuencia de números aleatorios.

In [ ]:
# Ejemplo sin seed
print(np.random.rand(3))  # [0.123, 0.456, 0.789] (diferente cada vez)
print(np.random.rand(3))  # [0.987, 0.654, 0.321] (siempre cambia)

[0.69910086 0.6346118  0.94493344]
[0.45791692 0.39993651 0.19168755]


In [ ]:
# Ejemplo con seed
np.random.seed(123)
# Pido 3 números (lee las primeras 3 líneas de la página 123)
print(np.random.rand(3))  # [0.696469, 0.286139, 0.226851] (siempre igual)

# Pido 3 números más (lee las siguientes 3 líneas)
print(np.random.rand(3))  # [0.551315, 0.719469, 0.423106] (siempre igual)

[0.69646919 0.28613933 0.22685145]
[0.55131477 0.71946897 0.42310646]


Explicado en términos simples: Cada vez que pides un número aleatorio, la computadora abre el libro en una página diferente (usando el reloj interno).  

**Con semilla:**  
np.random.seed(123) le dice a la computadora:  

"¡Abre el libro siempre en la página 123!"

Así siempre leerá los mismos números en el mismo orden.  
Al cambiar la semilla, cambian los números que se generan

In [ ]:
np.random.seed(42)
print(np.random.rand(3)) # [0.37454012 0.95071431 0.73199394]
print(np.random.rand(3)) # [0.59865848 0.15601864 0.15599452]

[0.37454012 0.95071431 0.73199394]
[0.59865848 0.15601864 0.15599452]


Y así los números se generan en base a la semilla proporcionada.

In [ ]:
arr_random = np.random.rand(10) # Esta línea genera 10 números aleatorios entre 0 y 9 (incluye 0 y excluye 10)
print(arr_random)
arr_random2 = np.random.rand(1, 11) # Esta línea genera 11 números aleatorios entre 1 y 11 excluyendo el 11
print(arr_random2)

[0.09767211 0.68423303 0.44015249 0.12203823 0.49517691 0.03438852
 0.9093204  0.25877998 0.66252228 0.31171108]
[[0.52006802 0.54671028 0.18485446 0.96958463 0.77513282 0.93949894
  0.89482735 0.59789998 0.92187424 0.0884925  0.19598286]]


### Otras funciones útiles

- np.unique(): devuelve valores únicos.
- np.round(): redondeo.
- np.argmax(): índice del valor máximo.
- np.argmin(): índice del valor mínimo.

In [ ]:
arr = np.array([1, 2, 2, 3, 4, 4, 5])
print("Valores únicos:", np.unique(arr))

print("Redondear π a 2 decimales:", np.round(np.pi, 2))

print("Índice del máximo:", arr.argmax())
print("Índice del mínimo:", arr.argmin())

Valores únicos: [1 2 3 4 5]
Redondear π a 2 decimales: 3.14
Índice del máximo: 6
Índice del mínimo: 0
